name: Deploy site

on:
  push:
    branches:
      - main
  repository_dispatch:
    event_type:
      - "sanity-deploy"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn Cache
        id: cache-yarn-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Install packages
        run: yarn
        if: |
          steps.cache-yarn-cache.outputs.cache-hit != 'true' ||
          steps.cache-node-modules.outputs.cache-hit != 'true'

      - name: Run build
        env:
          GATSBY_SANITY_ID: ${{ secrets.GATSBY_SANITY_ID }}
          GATSBY_SANITY_DATASET: ${{ secrets.GATSBY_SANITY_DATASET }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
          GATSBY_STRIPE_API_PUBLIC: ${{ secrets.GATSBY_STRIPE_API_PUBLIC }}
          GATSBY_STRIPE_API_SECRET: ${{ secrets.GATSBY_STRIPE_API_SECRET }}
          GATSBY_PRODUCTION_URL: ${{ secrets.GATSBY_PRODUCTION_URL }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_URL: ${{ secrets.MAILGUN_URL }}
          MAILGUN_RECIPIENT_EMAIL: ${{ secrets.MAILGUN_RECIPIENT_EMAIL }}

        run: yarn workspace site build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir=./site/public --prod
